/**
 * Single source of truth for every restaurant.
 *
 * Editing a store here updates it everywhere - there are no store details or
 * ordering links hardcoded anywhere else in the app:
 *
 * - `orderUrl`  → every "Order Now" / "Add to Cart" button on that store's
 *                 pages, the navbar and footer CTAs, and /order/[slug].
 *                 Resolved through `resolveOrderUrl()` / `useOrderUrl()`.
 *                 **Leave it as "" and that store falls back to ORDER_URL in
 *                 lib/constants.ts** (the brand-wide ordering page) - nothing
 *                 breaks, the buttons just point at the generic link.
 * - `address`   → the Google Maps embed and every "Get Directions" link
 *                 (FindFlamePopup, /locations, the navbar marquee).
 * - `slug`      → the /menu/[slug] and /catering/[slug] routes, generated by
 *                 generateStaticParams(). Adding a store here creates its
 *                 pages; no route file to add. See the slug rules below.
 * - `lat`/`lng` → nearest-store detection (GPS, IP, ZIP).
 *
 * So: to repoint a store's DoorDash link, change `orderUrl` here and every
 * button for that store follows. See docs/location-pages-guide.md.
 *
 * ---------------------------------------------------------------------------
 * SLUG FORMAT - one rule, no exceptions
 * ---------------------------------------------------------------------------
 *
 *     slug = kebab-case(name without its state) + "-" + lowercase(state)
 *
 *     "Laurel, MD"                    -> "laurel-md"
 *     "Royal Palm Beach, FL"          -> "royal-palm-beach-fl"
 *     "Forest Hill (Richmond), VA"    -> "forest-hill-richmond-va"
 *     "Northern Pkwy (Baltimore), MD" -> "northern-pkwy-baltimore-md"
 *
 * Derive it from `name`, NOT from `city`. `city` is the postal city and often
 * differs from what the store is called - the store everyone knows as
 * "Seven Corners" has `city: "Falls Church"`. Three slugs were previously
 * built from `city` (or with the words reversed), which meant a visitor on
 * /menu/falls-church-va saw a page headed "Seven Corners". They are now
 * seven-corners-va, forest-hill-richmond-va and northern-pkwy-baltimore-md.
 *
 * Punctuation - parentheses, commas, periods, "&" - collapses to a single "-".
 * No double hyphens, no leading/trailing hyphen.
 *
 * THE SLUG IS THE STORE'S PERMANENT URL IDENTITY. It is deliberately shared by
 * every location-scoped section, so one store is always the same word in every
 * URL it appears in:
 *
 *     /menu/laurel-md
 *     /catering/laurel-md
 *     /order/laurel-md
 *     /blog/laurel-md          <- a future section costs no new slug
 *
 * Adding a section later means adding a route that reads the same `slug`; it
 * does not mean inventing a second identifier. Build these paths with
 * `locationPath()` in lib/api/locations.ts rather than interpolating by hand,
 * so a new section only has to be registered in one place.
 *
 * Changing an existing slug changes a public URL. These pages have never been
 * deployed (production has no [location] routes yet), so the renames above
 * cost nothing. Once they are live, a rename needs a 301 from the old path in
 * next.config.mjs or it drops the page's search ranking and breaks shared
 * links.
 */
// Coordinates were address-matched with the U.S. Census geocoder's current
// address benchmark on 2026-08-11 and rounded to six decimal places. Keeping
// this precision supports accurate nearest-store calculations and GeoCoordinates
// structured data without implying survey-grade accuracy.
export const activeLocations = [
  {
    id: 1,
    slug: "baltimore-md",
    name: "Baltimore, MD",
    schemaName: "Flame Japanese Hibachi - Baltimore",
    address: "5230 Moravia Rd, Suite B, Baltimore, MD 21206",
    streetAddress: "5230 Moravia Rd, Suite B",
    city: "Baltimore",
    state: "MD",
    postalCode: "21206",
    phone: "+1 410-858-4910",
    hours: "Mon–Sat 11AM–10PM / Sun 11AM–9PM",
    lat: 39.323132,
    lng: -76.548982,
    image: "https://tile.openstreetmap.org/16/18831/24971.png",
    orderUrl: "https://order.online/store/flame-japanese-hibachi-5230-moravia-rd-ste-b-41690741",
  },
  {
    id: 2,
    slug: "manassas-va",
    name: "Manassas, VA",
    schemaName: "Flame Japanese Hibachi - Manassas",
    address: "9522 Liberia Ave, Manassas, VA 20110",
    streetAddress: "9522 Liberia Ave",
    city: "Manassas",
    state: "VA",
    postalCode: "20110",
    phone: "+1 703-789-8289",
    hours: "Mon–Sat 11AM–10PM / Sun 11AM–9PM",
    lat: 38.751264,
    lng: -77.44953,
    image: "https://tile.openstreetmap.org/16/18668/25104.png",
    orderUrl: "https://order.online/store/flame-japanese-hibachi-9522-liberia-ave-40449851",
  },
  {
    id: 3,
    slug: "laurel-md",
    name: "Laurel, MD",
    schemaName: "Flame Japanese Hibachi - Laurel",
    address: "13600 Baltimore Ave #310, Laurel, MD 20707",
    streetAddress: "13600 Baltimore Ave #310",
    city: "Laurel",
    state: "MD",
    postalCode: "20707",
    phone: "+1 240-360-5080",
    hours: "Mon–Sat 11AM–10PM / Sun 11AM–9PM",
    lat: 39.076327,
    lng: -76.868367,
    image: "https://tile.openstreetmap.org/16/18774/25027.png",
    orderUrl: "https://order.online/store/flame-japanese-hibachi-laurel-40839509",
  },
  {
    id: 4,
    slug: "pasadena-md",
    name: "Pasadena, MD",
    schemaName: "Flame Japanese Hibachi - Pasadena",
    address: "8036 Ritchie Hwy, Suite 1-C, Pasadena, MD 21122",
    streetAddress: "8036 Ritchie Hwy, Suite 1-C",
    city: "Pasadena",
    state: "MD",
    postalCode: "21122",
    phone: "+1 443-628-6850",
    hours: "Mon–Sat 11AM–10PM / Sun 11AM–9PM",
    lat: 39.12833,
    lng: -76.592018,
    image: "https://tile.openstreetmap.org/16/18825/25016.png",
    orderUrl: "https://order.online/store/flame-japanese-hibachi-pasadena-40976275",
  },
  {
    id: 5,
    slug: "alexandria-va",
    name: "Alexandria, VA",
    schemaName: "Flame Japanese Hibachi - Alexandria",
    address: "6676 Richmond Hwy, Alexandria, VA 22306",
    streetAddress: "6676 Richmond Hwy",
    city: "Alexandria",
    state: "VA",
    postalCode: "22306",
    phone: "+1 571-683-3199",
    hours: "Mon–Sat 11AM–10PM / Sun 11AM–9PM",
    lat: 38.772794,
    lng: -77.081418,
    image: "https://tile.openstreetmap.org/16/18735/25105.png",
    orderUrl: "https://order.online/store/flame-japanese-hibachi-richmond-hwy-40976321",
  },
  {
    id: 6,
    slug: "forest-hill-richmond-va",
    name: "Forest Hill (Richmond), VA",
    schemaName: "Flame Japanese Hibachi - Richmond",
    address: "7037 Forest Hill Avenue, Suite B, Richmond, VA 23225",
    streetAddress: "7037 Forest Hill Avenue, Suite B",
    city: "Richmond",
    state: "VA",
    postalCode: "23225",
    phone: "+1 804-997-7009",
    hours: "Mon–Sat 11AM–10PM / Sun 11AM–9PM",
    lat: 37.537703,
    lng: -77.524768,
    image: "https://tile.openstreetmap.org/16/18654/25385.png",
    orderUrl: "https://order.online/store/flame-japanese-hibachi-forest-hill-richmond-41163161",
  },
  {
    id: 7,
    slug: "tamarac-fl",
    name: "Tamarac, FL",
    schemaName: "Flame Japanese Hibachi - Tamarac",
    address: "5707 University Dr, Tamarac, FL 33321",
    streetAddress: "5707 University Dr",
    city: "Tamarac",
    state: "FL",
    postalCode: "33321",
    phone: "+1 954-953-8848",
    hours: "Mon–Sat 11AM–10PM / Sun 11AM–9PM",
    lat: 26.195305,
    lng: -80.25224,
    image: "https://tile.openstreetmap.org/16/18158/27823.png",
    orderUrl: "https://order.online/store/flame-hibachi-more-5707-n-university-dr-36348541",
  },
  {
    id: 8,
    slug: "seven-corners-va",
    name: "Seven Corners, VA",
    schemaName: "Flame Japanese Hibachi - Seven Corners",
    address: "6379 Seven Corners Center, VA 22044",
    streetAddress: "6379 Seven Corners Center",
    city: "Falls Church",
    state: "VA",
    postalCode: "22044",
    phone: "+1 571-480-5161",
    hours: "Mon–Sat 11AM–10PM / Sun 11AM–9PM",
    lat: 38.86929,
    lng: -77.1524002,
    image: "https://tile.openstreetmap.org/16/18722/25076.png",
    orderUrl: "https://order.online/store/flame-japanese-hibachi-6379-seven-corners-ctr-34585947",
  },
  {
    id: 9,
    slug: "northern-pkwy-baltimore-md",
    name: "Northern Pkwy (Baltimore), MD",
    schemaName: "Flame Japanese Hibachi - Baltimore Northern Parkway",
    address: "4460 W Northern Parkway, Baltimore, MD 21215",
    streetAddress: "4460 W Northern Parkway",
    city: "Baltimore",
    state: "MD",
    postalCode: "21215",
    phone: "+1 410-801-8279",
    hours: "Mon–Sat 11AM–10PM / Sun 11AM–9PM",
    lat: 39.344935,
    lng: -76.700561,
    image: "https://tile.openstreetmap.org/16/18807/24965.png",
    orderUrl: "https://order.online/store/flame-japanese-hibachi-4460-w-northern-parkway-32746289",
  },
  {
    id: 10,
    slug: "philadelphia-pa",
    name: "Philadelphia, PA",
    schemaName: "Flame Japanese Hibachi - Philadelphia",
    address: "101 E Olney Avenue, Philadelphia, PA 19120",
    streetAddress: "101 E Olney Avenue",
    city: "Philadelphia",
    state: "PA",
    postalCode: "19120",
    phone: "+1 215-344-6444",
    hours: "Mon–Sat 11AM–10PM / Sun 11AM–9PM",
    lat: 40.035252,
    lng: -75.120731,
    image: "https://tile.openstreetmap.org/16/19092/24802.png",
    orderUrl: "https://order.online/store/flame-hibachi-more-shop-320-101-e-olney-ave-32236185",
  },
  {
    id: 11,
    slug: "royal-palm-beach-fl",
    name: "Royal Palm Beach, FL",
    schemaName: "Flame Japanese Hibachi - Royal Palm Beach",
    address: "9940 Belvedere Rd #F, Royal Palm Beach, FL 33411",
    streetAddress: "9940 Belvedere Rd #F",
    city: "Royal Palm Beach",
    state: "FL",
    postalCode: "33411",
    phone: "+1 561-766-1038",
    hours: "Mon–Sat 11AM–10PM / Sun 11AM–9PM",
    lat: 26.69149,
    lng: -80.198611,
    image: "https://tile.openstreetmap.org/16/18167/27723.png",
    orderUrl: "https://order.online/store/flame-japanese-hibachi-9940-belvedere-rd-ste-f-32295195",
  },
  {
    id: 12,
    slug: "aberdeen-md",
    name: "Aberdeen, MD",
    schemaName: "Flame Japanese Hibachi - Aberdeen",
    address: "939 Beards Hill Rd, Aberdeen, MD 21001",
    streetAddress: "939 Beards Hill Rd",
    city: "Aberdeen",
    state: "MD",
    postalCode: "21001",
    phone: "+1 443-327-8349",
    hours: "Mon–Sat 11AM–10PM / Sun 11AM–9PM",
    lat: 39.525004,
    lng: -76.183636,
    image: "https://tile.openstreetmap.org/16/18898/24922.png",
    orderUrl: "https://order.online/store/flame-japanese-hibachi-939-beards-hill-rd-35850649",
  },
  {
    id: 13,
    slug: "mechanicsville-va",
    name: "Mechanicsville, VA",
    schemaName: "Flame Japanese Hibachi - Mechanicsville",
    address: "7354 Bell Creek Rd, Mechanicsville, VA 23111",
    streetAddress: "7354 Bell Creek Rd",
    city: "Mechanicsville",
    state: "VA",
    postalCode: "23111",
    phone: "+1 804-789-8540",
    hours: "Mon–Sat 11AM–10PM / Sun 11AM–9PM",
    lat: 37.60425,
    lng: -77.354333,
    image: "https://tile.openstreetmap.org/16/18687/25371.png",
    orderUrl: "https://order.online/store/flame-hibachi-mechanicsville-46004389",
  },
  {
    id: 14,
    slug: "bristow-va",
    name: "Bristow, VA",
    schemaName: "Flame Japanese Hibachi - Bristow",
    address: "10286 Bristow Center Dr, Bristow, VA 20136",
    streetAddress: "10286 Bristow Center Dr",
    city: "Bristow",
    state: "VA",
    postalCode: "20136",
    phone: "+1 703-420-2339",
    hours: "Mon–Sat 11AM–10PM / Sun 11AM–9PM",
    lat: 38.73296,
    lng: -77.550344,
    image: "https://tile.openstreetmap.org/16/18651/25109.png",
    orderUrl: "", // TODO(order-url): paste bristow-va order.online URL here
  },
];

export const comingSoonLocations = [
  {
    id: 1,
    name: "Miami, FL",
    address: "11195 SW 216th St, Miami, FL 33170",
    status: "Coming Soon",
    openUntil: "11 PM",
    distance: "2.4 MILES AWAY",
  },
  {
    id: 2,
    name: "Marlow Heights, MD",
    address: "4620 St Barnabas Rd, Suite #B, Marlow Heights, MD 20748",
    status: "Coming Soon",
    openUntil: "10 PM",
    distance: "4.8 MILES AWAY",
  },
  {
    id: 3,
    name: "Norfolk, VA",
    address: "5802 E Virginia Blvd, Space #130, Norfolk, VA 23502",
    status: "Coming Soon",
    openUntil: "11 PM",
    distance: "5.2 MILES AWAY",
  },
  {
    id: 6,
    name: "Bowie, MD",
    address: "3548 Crain Highway, Bowie, MD 20716",
    status: "Coming Soon",
    openUntil: "11 PM",
    distance: "2.9 MILES AWAY",
  },
  {
    id: 7,
    name: "Coral Springs, FL",
    address: "6291 West Sample Rd, Coral Springs, FL 33067",
    status: "Coming Soon",
    openUntil: "10 PM",
    distance: "6.1 MILES AWAY",
  },
  {
    id: 8,
    name: "Fredericksburg, VA",
    address: "5711 Plank Rd, Fredericksburg, VA 22407",
    status: "Coming Soon",
    openUntil: "11 PM",
    distance: "4.2 MILES AWAY",
  },
  {
    id: 9,
    name: "Accokeek, MD",
    address: "7045C Berry Road, Accokeek, MD 20607",
    status: "Coming Soon",
    openUntil: "10 PM",
    distance: "3.3 MILES AWAY",
  },
];
